CREATE TABLE IF NOT EXISTS `Scores` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `userID` int,
    `Scores` int,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`userID`) REFERENCES User(`id`)
)